### ISSUE TITLE
Error while loading recipes

### ISSUE THREAD

**Issue by Bedrocks** [CloudburstMC/Cloudburst#64]
When you start the server, you will get errors while all recipes are loading:

```
21:58:24 [INFO ] Loading recipes...
21:58:24 [ERROR] Exception during registering recipe: {id=minecraft:campfire_from_log2, type=1, input={A={id=280, damage=-1}, B={id=263, damage=-1}, C={id=162, damage=-1}}, output=[], shape=[ A , ABA, CCC], block=crafting_table, priority=2}
java.lang.NullPointerException: null
	at org.cloudburstmc.server.item.behavior.BlockItem.<init>(BlockItem.java:17) ~[classes/:?]
	at org.cloudburstmc.server.registry.ItemRegistry.getItem(ItemRegistry.java:111) ~[classes/:?]
	at org.cloudburstmc.server.item.behavior.Item.get(Item.java:148) ~[classes/:?]
	at org.cloudburstmc.server.item.behavior.Item.get(Item.java:175) ~[classes/:?]
	at org.cloudburstmc.server.item.behavior.Item.fromJson(Item.java:226) ~[classes/:?]
	at org.cloudburstmc.server.inventory.CraftingManager.loadRecipes(CraftingManager.java:195) ~[classes/:?]
	at org.cloudburstmc.server.inventory.CraftingManager.<init>(CraftingManager.java:58) ~[classes/:?]
	at org.cloudburstmc.server.inventory.CraftingManager$$FastClassByGuice$$686a7fd1.newInstance(<generated>) ~[classes/:?]
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1094) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1131) ~[guice-4.2.3.jar:?]
	at org.cloudburstmc.server.Server.<init>(Server.java:240) ~[classes/:?]
	at org.cloudburstmc.server.Nukkit.main(Nukkit.java:146) ~[classes/:?]
21:58:24 [ERROR] Exception during registering recipe: {id=minecraft:grindstone_from_crimson_planks2, type=1, input={A={id=280, damage=-1}, B={id=182, damage=-1}, C={id=-242, damage=-1}}, output=[], shape=[ABA, C C], block=crafting_table, priority=2}
java.lang.NullPointerException: null
	at org.cloudburstmc.server.item.behavior.BlockItem.<init>(BlockItem.java:17) ~[classes/:?]
	at org.cloudburstmc.server.registry.ItemRegistry.getItem(ItemRegistry.java:111) ~[classes/:?]
	at org.cloudburstmc.server.item.behavior.Item.get(Item.java:148) ~[classes/:?]
	at org.cloudburstmc.server.item.behavior.Item.get(Item.java:175) ~[classes/:?]
	at org.cloudburstmc.server.item.behavior.Item.fromJson(Item.java:226) ~[classes/:?]
	at org.cloudburstmc.server.inventory.CraftingManager.loadRecipes(CraftingManager.java:195) ~[classes/:?]
	at org.cloudburstmc.server.inventory.CraftingManager.<init>(CraftingManager.java:58) ~[classes/:?]
	at org.cloudburstmc.server.inventory.CraftingManager$$FastClassByGuice$$686a7fd1.newInstance(<generated>) ~[classes/:?]
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1094) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1131) ~[guice-4.2.3.jar:?]
	at org.cloudburstmc.server.Server.<init>(Server.java:240) ~[classes/:?]
	at org.cloudburstmc.server.Nukkit.main(Nukkit.java:146) ~[classes/:?]
21:58:24 [ERROR] Exception during registering recipe: {id=minecraft:grindstone_from_crimson_planks3, type=1, input={A={id=280, damage=-1}, B={id=-162, damage=-1}, C={id=-242, damage=-1}}, output=[], shape=[ABA, C C], block=crafting_table, priority=2}
java.lang.NullPointerException: null
	at org.cloudburstmc.server.item.behavior.BlockItem.<init>(BlockItem.java:17) ~[classes/:?]
	at org.cloudburstmc.server.registry.ItemRegistry.getItem(ItemRegistry.java:111) ~[classes/:?]
	at org.cloudburstmc.server.item.behavior.Item.get(Item.java:148) ~[classes/:?]
	at org.cloudburstmc.server.item.behavior.Item.get(Item.java:175) ~[classes/:?]
	at org.cloudburstmc.server.item.behavior.Item.fromJson(Item.java:226) ~[classes/:?]
	at org.cloudburstmc.server.inventory.CraftingManager.loadRecipes(CraftingManager.java:195) ~[classes/:?]
	at org.cloudburstmc.server.inventory.CraftingManager.<init>(CraftingManager.java:58) ~[classes/:?]
	at org.cloudburstmc.server.inventory.CraftingManager$$FastClassByGuice$$686a7fd1.newInstance(<generated>) ~[classes/:?]
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1094) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1131) ~[guice-4.2.3.jar:?]
	at org.cloudburstmc.server.Server.<init>(Server.java:240) ~[classes/:?]
	at org.cloudburstmc.server.Nukkit.main(Nukkit.java:146) ~[classes/:?]
21:58:24 [ERROR] Exception during registering recipe: {id=minecraft:grindstone_from_crimson_planks4, type=1, input={A={id=280, damage=-1}, B={id=-166, damage=-1}, C={id=-242, damage=-1}}, output=[], shape=[ABA, C C], block=crafting_table, priority=2}
java.lang.NullPointerException: null
	at org.cloudburstmc.server.item.behavior.BlockItem.<init>(BlockItem.java:17) ~[classes/:?]
	at org.cloudburstmc.server.registry.ItemRegistry.getItem(ItemRegistry.java:111) ~[classes/:?]
	at org.cloudburstmc.server.item.behavior.Item.get(Item.java:148) ~[classes/:?]
	at org.cloudburstmc.server.item.behavior.Item.get(Item.java:175) ~[classes/:?]
	at org.cloudburstmc.server.item.behavior.Item.fromJson(Item.java:226) ~[classes/:?]
	at org.cloudburstmc.server.inventory.CraftingManager.loadRecipes(CraftingManager.java:195) ~[classes/:?]
	at org.cloudburstmc.server.inventory.CraftingManager.<init>(CraftingManager.java:58) ~[classes/:?]
	at org.cloudburstmc.server.inventory.CraftingManager$$FastClassByGuice$$686a7fd1.newInstance(<generated>) ~[classes/:?]
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1094) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1131) ~[guice-4.2.3.jar:?]
	at org.cloudburstmc.server.Server.<init>(Server.java:240) ~[classes/:?]
	at org.cloudburstmc.server.Nukkit.main(Nukkit.java:146) ~[classes/:?]
21:58:24 [ERROR] Exception during registering recipe: {id=minecraft:grindstone_from_warped_planks2, type=1, input={A={id=280, damage=-1}, B={id=182, damage=-1}, C={id=-243, damage=-1}}, output=[], shape=[ABA, C C], block=crafting_table, priority=2}
java.lang.NullPointerException: null
	at org.cloudburstmc.server.item.behavior.BlockItem.<init>(BlockItem.java:17) ~[classes/:?]
	at org.cloudburstmc.server.registry.ItemRegistry.getItem(ItemRegistry.java:111) ~[classes/:?]
	at org.cloudburstmc.server.item.behavior.Item.get(Item.java:148) ~[classes/:?]
	at org.cloudburstmc.server.item.behavior.Item.get(Item.java:175) ~[classes/:?]
	at org.cloudburstmc.server.item.behavior.Item.fromJson(Item.java:226) ~[classes/:?]
	at org.cloudburstmc.server.inventory.CraftingManager.loadRecipes(CraftingManager.java:195) ~[classes/:?]
	at org.cloudburstmc.server.inventory.CraftingManager.<init>(CraftingManager.java:58) ~[classes/:?]
	at org.cloudburstmc.server.inventory.CraftingManager$$FastClassByGuice$$686a7fd1.newInstance(<generated>) ~[classes/:?]
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1094) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1131) ~[guice-4.2.3.jar:?]
	at org.cloudburstmc.server.Server.<init>(Server.java:240) ~[classes/:?]
	at org.cloudburstmc.server.Nukkit.main(Nukkit.java:146) ~[classes/:?]
21:58:24 [ERROR] Exception during registering recipe: {id=minecraft:grindstone_from_warped_planks3, type=1, input={A={id=280, damage=-1}, B={id=-162, damage=-1}, C={id=-243, damage=-1}}, output=[], shape=[ABA, C C], block=crafting_table, priority=2}
java.lang.NullPointerException: null
	at org.cloudburstmc.server.item.behavior.BlockItem.<init>(BlockItem.java:17) ~[classes/:?]
	at org.cloudburstmc.server.registry.ItemRegistry.getItem(ItemRegistry.java:111) ~[classes/:?]
	at org.cloudburstmc.server.item.behavior.Item.get(Item.java:148) ~[classes/:?]
	at org.cloudburstmc.server.item.behavior.Item.get(Item.java:175) ~[classes/:?]
	at org.cloudburstmc.server.item.behavior.Item.fromJson(Item.java:226) ~[classes/:?]
	at org.cloudburstmc.server.inventory.CraftingManager.loadRecipes(CraftingManager.java:195) ~[classes/:?]
	at org.cloudburstmc.server.inventory.CraftingManager.<init>(CraftingManager.java:58) ~[classes/:?]
	at org.cloudburstmc.server.inventory.CraftingManager$$FastClassByGuice$$686a7fd1.newInstance(<generated>) ~[classes/:?]
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1094) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1131) ~[guice-4.2.3.jar:?]
	at org.cloudburstmc.server.Server.<init>(Server.java:240) ~[classes/:?]
	at org.cloudburstmc.server.Nukkit.main(Nukkit.java:146) ~[classes/:?]
21:58:24 [ERROR] Exception during registering recipe: {id=minecraft:grindstone_from_warped_planks4, type=1, input={A={id=280, damage=-1}, B={id=-166, damage=-1}, C={id=-243, damage=-1}}, output=[], shape=[ABA, C C], block=crafting_table, priority=2}
java.lang.NullPointerException: null
	at org.cloudburstmc.server.item.behavior.BlockItem.<init>(BlockItem.java:17) ~[classes/:?]
	at org.cloudburstmc.server.registry.ItemRegistry.getItem(ItemRegistry.java:111) ~[classes/:?]
	at org.cloudburstmc.server.item.behavior.Item.get(Item.java:148) ~[classes/:?]
	at org.cloudburstmc.server.item.behavior.Item.get(Item.java:175) ~[classes/:?]
	at org.cloudburstmc.server.item.behavior.Item.fromJson(Item.java:226) ~[classes/:?]
	at org.cloudburstmc.server.inventory.CraftingManager.loadRecipes(CraftingManager.java:195) ~[classes/:?]
	at org.cloudburstmc.server.inventory.CraftingManager.<init>(CraftingManager.java:58) ~[classes/:?]
	at org.cloudburstmc.server.inventory.CraftingManager$$FastClassByGuice$$686a7fd1.newInstance(<generated>) ~[classes/:?]
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1094) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1131) ~[guice-4.2.3.jar:?]
	at org.cloudburstmc.server.Server.<init>(Server.java:240) ~[classes/:?]
	at org.cloudburstmc.server.Nukkit.main(Nukkit.java:146) ~[classes/:?]
21:58:24 [ERROR] Exception during registering recipe: {id=minecraft:smoker_from_log2, type=1, input={A={id=162, damage=-1}, B={id=61, damage=-1}}, output=[], shape=[ A , ABA,  A ], block=crafting_table, priority=0}
java.lang.NullPointerException: null
	at org.cloudburstmc.server.item.behavior.BlockItem.<init>(BlockItem.java:17) ~[classes/:?]
	at org.cloudburstmc.server.registry.ItemRegistry.getItem(ItemRegistry.java:111) ~[classes/:?]
	at org.cloudburstmc.server.item.behavior.Item.get(Item.java:148) ~[classes/:?]
	at org.cloudburstmc.server.item.behavior.Item.get(Item.java:175) ~[classes/:?]
	at org.cloudburstmc.server.item.behavior.Item.fromJson(Item.java:226) ~[classes/:?]
	at org.cloudburstmc.server.inventory.CraftingManager.loadRecipes(CraftingManager.java:195) ~[classes/:?]
	at org.cloudburstmc.server.inventory.CraftingManager.<init>(CraftingManager.java:58) ~[classes/:?]
	at org.cloudburstmc.server.inventory.CraftingManager$$FastClassByGuice$$686a7fd1.newInstance(<generated>) ~[classes/:?]
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1094) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1131) ~[guice-4.2.3.jar:?]
	at org.cloudburstmc.server.Server.<init>(Server.java:240) ~[classes/:?]
	at org.cloudburstmc.server.Nukkit.main(Nukkit.java:146) ~[classes/:?]
21:58:24 [ERROR] Exception during registering recipe: {id=minecraft:soul_campfire_from_soul_sand_and_log2, type=1, input={A={id=280, damage=-1}, B={id=88, damage=-1}, C={id=162, damage=-1}}, output=[], shape=[ A , ABA, CCC], block=crafting_table, priority=2}
java.lang.NullPointerException: null
	at org.cloudburstmc.server.item.behavior.BlockItem.<init>(BlockItem.java:17) ~[classes/:?]
	at org.cloudburstmc.server.registry.ItemRegistry.getItem(ItemRegistry.java:111) ~[classes/:?]
	at org.cloudburstmc.server.item.behavior.Item.get(Item.java:148) ~[classes/:?]
	at org.cloudburstmc.server.item.behavior.Item.get(Item.java:175) ~[classes/:?]
	at org.cloudburstmc.server.item.behavior.Item.fromJson(Item.java:226) ~[classes/:?]
	at org.cloudburstmc.server.inventory.CraftingManager.loadRecipes(CraftingManager.java:195) ~[classes/:?]
	at org.cloudburstmc.server.inventory.CraftingManager.<init>(CraftingManager.java:58) ~[classes/:?]
	at org.cloudburstmc.server.inventory.CraftingManager$$FastClassByGuice$$686a7fd1.newInstance(<generated>) ~[classes/:?]
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1094) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1131) ~[guice-4.2.3.jar:?]
	at org.cloudburstmc.server.Server.<init>(Server.java:240) ~[classes/:?]
	at org.cloudburstmc.server.Nukkit.main(Nukkit.java:146) ~[classes/:?]
21:58:24 [ERROR] Exception during registering recipe: {id=minecraft:soul_campfire_from_soul_soil_and_log2, type=1, input={A={id=280, damage=-1}, B={id=-236, damage=-1}, C={id=162, damage=-1}}, output=[], shape=[ A , ABA, CCC], block=crafting_table, priority=2}
java.lang.NullPointerException: null
	at org.cloudburstmc.server.item.behavior.BlockItem.<init>(BlockItem.java:17) ~[classes/:?]
	at org.cloudburstmc.server.registry.ItemRegistry.getItem(ItemRegistry.java:111) ~[classes/:?]
	at org.cloudburstmc.server.item.behavior.Item.get(Item.java:148) ~[classes/:?]
	at org.cloudburstmc.server.item.behavior.Item.get(Item.java:175) ~[classes/:?]
	at org.cloudburstmc.server.item.behavior.Item.fromJson(Item.java:226) ~[classes/:?]
	at org.cloudburstmc.server.inventory.CraftingManager.loadRecipes(CraftingManager.java:195) ~[classes/:?]
	at org.cloudburstmc.server.inventory.CraftingManager.<init>(CraftingManager.java:58) ~[classes/:?]
	at org.cloudburstmc.server.inventory.CraftingManager$$FastClassByGuice$$686a7fd1.newInstance(<generated>) ~[classes/:?]
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1094) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1131) ~[guice-4.2.3.jar:?]
	at org.cloudburstmc.server.Server.<init>(Server.java:240) ~[classes/:?]
	at org.cloudburstmc.server.Nukkit.main(Nukkit.java:146) ~[classes/:?]
21:58:25 [INFO ] Loaded 1615 recipes.
```

Example for minecraft:campfire_from_log2

1)
![image](https://user-images.githubusercontent.com/28847468/94063948-2e0c8080-fde9-11ea-8bad-b5164c23d632.png)

2)
![image](https://user-images.githubusercontent.com/28847468/94063983-3f558d00-fde9-11ea-999f-5f5ebd930ddf.png)

3) state null cause the error
![image](https://user-images.githubusercontent.com/28847468/94064102-70ce5880-fde9-11ea-9c58-389b1788fd8b.png)

4) called here (line 111):
![image](https://user-images.githubusercontent.com/28847468/94064308-c73b9700-fde9-11ea-921b-b57063ccb236.png)

5) maybe because of damage -1?:
![image](https://user-images.githubusercontent.com/28847468/94064420-f94cf900-fde9-11ea-98e7-4b00a454ada5.png)

**Comment by Sleepybear** [comment]
This is from the fact that `minecraft:log2`, among other blocks, are not yet implemented nor registered. 

We should probably fail with a warning instead of printing a full error stack?
